env: staging
address:
  internal: 'http://127.0.0.1:8001'
  external: 'http://127.0.0.1:8001'
  test: 'http://127.0.0.1:8001'
sql:
  database: 'moyklass'
  username: 'test'
  password: 'test'
  options :
    host: '127.0.0.1'
    port: 5432
    dialect: 'postgres'
    logging: false
    operatorsAliases: false
    define:
      timestamps: false
    pool:
      max: 5
      min: 0
      acquire: 30000
      idle: 10000
cors: '*'
